[env:blackpill_f411ce]
platform = ststm32
board = blackpill_f411ce
framework = arduino
monitor_filters = direct
build_flags =
    -D USBCON
    -D USBD_USE_CDC
    -Ofast
    -DARM_MATH_CM4
    -D__FPU_PRESENT=1